### ISSUE TITLE
Cannot create mask for step 1 

### ISSUE THREAD

**Issue by nukadelic** [s9roll7/ebsynth_utility#10]
I have install WebUI and the extension when my files where on the desktop , but then i moved everything to the Drive root , looks like its using an old path for some reason ( at 3rd last line in the logs below ) , tried restarted the machine but didn't seem to help. 
Video frame folder is being populated correctly , but the video_mask folder is empty , logs :
```
...
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\StableDiffusion\Projects\one\video_frame\%05d.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.4.100
  Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 852x480 [SAR 640:639 DAR 16:9], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.6.100 png
frame=   38 fps=0.0 q=-0.0 Lsize=N/A time=00:00:01.54 bitrate=N/A speed=9.09x    ts/s speed=N/A
video:9268kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
frame extracted
Fatal error in launcher: Unable to create process using '"C:\Users\Stealth\Desktop\SDWebUI\venv\Scripts\python.exe"  "C:\StableDiffusion\SDWebUI\venv\Scripts\transparent-background.exe" --source C:\StableDiffusion\Projects\one\video_frame --dest C:\StableDiffusion\Projects\one\video_mask --type map': The system cannot find the file specified.

mask created

completed.
```

**Comment by s9roll7** [comment]
You're using python in an odd place.
I think it would be faster to redo the installation honestly.

**Comment by screan** [comment]
@nukadelic this happened to me at first to. just run

pip install transparent-background

**Comment by nukadelic** [comment]
@s9roll7 reinstalled everything , but seems like it wants to install some sort of pth file , not sure what to make of it ,
also tried installing transparent-background as @screan suggested , but didn't help
```
Skip frame extraction
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY

Traceback (most recent call last):
  File "C:\Dev\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Dev\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\StableDiffusion\Auto1111\venv\Scripts\transparent-background.exe\__main__.py", line 7, in <module>
  File "C:\StableDiffusion\Auto1111\venv\lib\site-packages\transparent_background\Remover.py", line 151, in console
    remover = Remover(fast=args.fast, jit=args.jit, device=args.device, ckpt=args.ckpt)
  File "C:\StableDiffusion\Auto1111\venv\lib\site-packages\transparent_background\Remover.py", line 79, in __init__
    self.model.load_state_dict(torch.load(os.path.join(ckpt_dir, ckpt_name), map_location='cpu'), strict=True)
  File "C:\StableDiffusion\Auto1111\venv\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\StableDiffusion\Auto1111\venv\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\StableDiffusion\Auto1111\venv\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Stealth\\.transparent-background\\ckpt_base.pth'
mask created

completed.
```

**Comment by nukadelic** [comment]
oh nvm , i think i got it , just needed to manually dl and rename the file , more info here ( see [issue 26](https://github.com/s9roll7/ebsynth_utility/issues/26) ) , any ideas what is this file , and why do we need to download from someone else's google drive ?

**Comment by s9roll7** [comment]
https://github.com/plemeri/InSPyReNet
I believe that file is a pre-trained model used internally by transparent-background

**Comment by nukadelic** [comment]
@s9roll7 found a way to fix that , in stage1 , create_mask_transparent_background :
```py
    fast_str = " --fast" if tb_use_fast_mode else ""
    jit_str = " --jit" if tb_use_jit else ""
    bin_path = os.path.join("venv", "Scripts")
    bin_path = os.path.join(bin_path, "transparent-background.exe")
    print("--> Bin = " + bin_path ) 
 
    # if os.path.isfile(bin_path) or os.path.isfile(bin_path + ".exe"):
    #     print("local")
    #     subprocess.call(bin_path + " --source " + input_dir + " --dest " + output_dir + " --type map" + fast_str + jit_str, shell=True)
    # else:
    #     print("global")
    #     subprocess.call("transparent-background --source " + input_dir + " --dest " + output_dir + " --type map" + fast_str + jit_str, shell=True)

    current_dir = os.path.abspath(__file__)

    print("--> Current Dir = " + current_dir )

    a1111_dir = os.path.abspath( os.path.abspath( os.path.dirname( current_dir ) + "/../" ) + "/../" )
    print("--> A1111 Dir = " + a1111_dir )

    py_dir = os.path.join( a1111_dir , "venv" , "Scripts", "python.exe" )
    print("--> Py Dir = " + py_dir )

    exe_dir = os.path.join( a1111_dir , bin_path )
    print("--> Exec Dir = " + exe_dir )

    cmd_out = py_dir + " " + exe_dir + " --source " + input_dir + " --dest " + output_dir + " --type map" + fast_str + jit_str
    print( "--> Invoke: " + cmd_out )
    
    # subprocess.call( exe_dir + " --source " + input_dir + " --dest " + output_dir + " --type map" + fast_str + jit_str, cwd=a1111_dir, shell=True)
    
    os.system( cmd_out )
    
    # rest of the method is unchanged 

    mask_imgs = ...
```
