### ISSUE TITLE
 AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'mask_blur'

### ISSUE THREAD

**Issue by UriahKong** [s9roll7/ebsynth_utility#103]
Bro,I got a problem at stage 3, everytime I activate ebsynth utility script and the commander shows :
`Loading model from cache: control_v11p_sd15_softedge [a8575a2a]
*** Error running process: C:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 519, in process
        script.process(p, *script_args)
      File "C:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1126, in process
        if p.mask_blur > 0:
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'mask_blur'`
but I can use img2img function nomally,only the script goes wrong ,plz help me ,my dear friend 

>

**Comment by UriahKong** [comment]
I haven't used for a day ,now im crying in my room , so skeptical of love~~Is there anybody

**Comment by UriahKong** [comment]
请问有没有善长仁翁帮小弟把把关,我好几天没搞定这个,谷歌也搜不到鸭呜呜呜~
Now im crying in my room~so skeptical of love ,and I want solutions~~~if u catch my drift~

**Comment by UriahKong** [comment]
请问有没有善长仁翁帮小弟把把关,我好几天没搞定这个,谷歌也搜不到鸭呜呜呜~
Now im crying in my room,so skeptical of love ,and I want solutions~if u catch my drift
