### ISSUE TITLE
error when enabling yunet face detect

### ISSUE THREAD

**Issue by chuckkay** [s9roll7/ebsynth_utility#109]
Traceback (most recent call last):
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\modules\img2img.py", line 218, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\modules\scripts.py", line 605, in run
        processed = script.run(p, *script_args)
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\extensions\ebsynth_utility\scripts\custom_script.py", line 906, in run
        face_coords = self.detect_face(image, mask_image, face_detection_method, max_crop_size)
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\extensions\ebsynth_utility\scripts\custom_script.py", line 222, in detect_face
        faces = self.detect_face_from_img(img_array)
      File "C:\AI\Automatic-SDXXXL\stable-diffusion-webui\extensions\ebsynth_utility\scripts\custom_script.py", line 170, in detect_face_from_img
        _, result = self.face_detector.detect(img_array)
    cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.cpp:279: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerData'

**Comment by laohan9** [comment]
I also encountered the same problem, I hope someone can answer it

**Comment by acolasialiuliu** [comment]
TypeError: download_and_cache_models() takes 0 positional arguments but 1 was given
