### ISSUE TITLE
stage 1 mask making erro

### ISSUE THREAD

**Issue by galacticequus** [s9roll7/ebsynth_utility#116]
```python
Settings -> Mode=base, Device=cuda, Torchscript=disabled
00001.png:       0%|                                                  | 0/717 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: (0, 'C:\\Users\\3070P\\Desktop\\myebsynth', 'C:\\Users\\3070P\\AppData\\Local\\Temp\\gradio\\37c007508138b3aab56f8b546adb7a8685799912\\demo.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
    Traceback (most recent call last):
      File "C:\Users\3070P\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\3070P\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\3070P\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
        ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
      File "C:\Users\3070P\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 207, in ebsynth_utility_stage1
        create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
      File "C:\Users\3070P\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 161, in create_mask_transparent_background
        out[out < int( 255 * st1_mask_threshold )] = 0
    TypeError: '<' not supported between instances of 'Image' and 'int'
``` 
here is it,i reinstalled ebsynth extension and transparent_background both,but same wrong still here,any help?

**Comment by Serkad** [comment]
same error

**Comment by yakjang** [comment]
me too.

**Comment by shakir-abdo** [comment]
me too ..
