### ISSUE TITLE
This is an import error that occurred during the execution of a Python program.

### ISSUE THREAD

**Issue by A3734** [s9roll7/ebsynth_utility#142]
dear all
Since yesterday, the following error message has suddenly started appearing while running Stable Diffusion:
↓
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 23, in imports
    import gradio  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 40, in <module>
    from pydantic import BaseModel, parse_obj_as
  File "/usr/local/lib/python3.10/dist-packages/pydantic/__init__.py", line 395, in __getattr__
    module = import_module(module_name, package=package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 17, in <module>
    from ._internal import (
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_decorators.py", line 15, in <module>
    from ._core_utils import get_type_ref
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_core_utils.py", line 14, in <module>
    from pydantic_core import validate_core_schema as _validate_core_schema
ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (/usr/local/lib/python3.10/dist-packages/pydantic_core/__init__.py)

**Comment by A3734** [comment]
I am using stable diffusion in a colab environment. The above error message appears and I cannot install ebsynth_utility. Could someone please provide me with a code that can solve this issue? Thank you in advance.
