### ISSUE TITLE
求助，ebsynth_utility不生成蒙版图像/Request assistance，ebsynth_utility Do not generate mask images！

### ISSUE THREAD

**Issue by wocNBdaniuma** [s9roll7/ebsynth_utility#149]
ffmpeg配置好了
![微信图片_20240907163952](https://github.com/user-attachments/assets/6039d65b-7484-4e55-ad58-c5ddf4d972d0)
transparent-background安装了
![微信图片_20240907163955](https://github.com/user-attachments/assets/839ad448-efe0-4025-a458-c549148ec61c)
放置了ckpt_fast.pth
![微信图片_20240907163958](https://github.com/user-attachments/assets/0303fcef-954d-4849-b4cf-db3d99594189)
可以正常生成帧序列，但是不能生成蒙版，以下是代码
![微信图片_20240907164145](https://github.com/user-attachments/assets/80043d56-bbe2-4f6d-afef-1417a697fa48)
不清楚什么问题，sd的python和我电脑的python都安装过transparent-background，求助大佬这什么情况啊

**Comment by wocNBdaniuma** [comment]
Error completing request
*** Arguments: (0, 'E:\\gcwj\\dfg', 'C:\\Users\\YYY\\AppData\\Local\\Temp\\gradio\\951c8c06f5236e84d583443cc4a59084e88d674e\\guang.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
    Traceback (most recent call last):
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
        ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\extensions\ebsynth_utility\stage1.py", line 209, in ebsynth_utility_stage1
        create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\extensions\ebsynth_utility\stage1.py", line 151, in create_mask_transparent_background
        remover = Remover(fast=tb_use_fast_mode, jit=tb_use_jit, device=devices.get_optimal_device_name())
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\transparent_background\Remover.py", line 88, in __init__
        wget.download(self.meta.url, os.path.join(ckpt_dir, ckpt_name))
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\wget.py", line 526, in download
        (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 241, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\urllib\request.py", line 1352, in do_open
        r = h.getresponse()
      File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 129, in getresponse
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\http\client.py", line 1375, in getresponse
        response.begin()
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\http\client.py", line 318, in begin
        version, status, reason = self._read_status()
      File "F:\Design\sd-webui-aki\sd-webui-aki-v4.8\python\lib\http\client.py", line 287, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    http.client.RemoteDisconnected: Remote end closed connection without response
弹了一段新的代码，我看不懂

**Comment by wocNBdaniuma** [comment]
解决了，把通过国内镜像下载关了，开全局代理，我现在想把我问的这个睿智问题删掉

**Comment by willanki** [comment]
> 解决了，把通过国内镜像下载关了，开全局代理，我现在想把我问的这个睿智问题删掉
大佬，同样问题，之前好好的，突然就报错了，所有镜像都关掉吗？包括transparent_background也需要重新下载吗
