### ISSUE TITLE
求助 TypeError: Remover.__init__() got an unexpected keyword argument 'fast'

### ISSUE THREAD

**Issue by bournegu** [s9roll7/ebsynth_utility#150]
![Uploading 微信截图_20241012163318.png…]()

**Comment by bournegu** [comment]
*** Error completing request
*** Arguments: (0, 'C:\\Users\\bowen\\Desktop\\project009', 'C:\\Users\\bowen\\AppData\\Local\\Temp\\gradio\\0dcd4ec78849490b31006164bfd3e8031fb5068b\\project009.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
        ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
      File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\extensions\ebsynth_utility\stage1.py", line 209, in ebsynth_utility_stage1
        create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
      File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\extensions\ebsynth_utility\stage1.py", line 151, in create_mask_transparent_background
        remover = Remover(fast=tb_use_fast_mode, jit=tb_use_jit, device=devices.get_optimal_device_name())
    TypeError: Remover.__init__() got an unexpected keyword argument 'fast'

**Comment by bournegu** [comment]
pip install transparent-background==1.3.2 卸载安装这个版本

**Comment by DotPoker2** [comment]
> *** Error completing request *** Arguments: (0, 'C:\Users\bowen\Desktop\project009', 'C:\Users\bowen\AppData\Local\Temp\gradio\0dcd4ec78849490b31006164bfd3e8031fb5068b\project009.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {} Traceback (most recent call last): File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\modules\call_queue.py", line 74, in f res = list(func(*args, **kwargs)) File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\modules\call_queue.py", line 53, in f res = func(*args, **kwargs) File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\modules\call_queue.py", line 37, in f res = func(*args, **kwargs) File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask) File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\extensions\ebsynth_utility\stage1.py", line 209, in ebsynth_utility_stage1 create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold) File "D:\sd-webui-aki-v4.9\sd-webui-aki-v4.9\extensions\ebsynth_utility\stage1.py", line 151, in create_mask_transparent_background remover = Remover(fast=tb_use_fast_mode, jit=tb_use_jit, device=devices.get_optimal_device_name()) TypeError: Remover.**init**() got an unexpected keyword argument 'fast'

getting the same error, wanting help, as i'm really wanting to try video making with a1111.

**Comment by DotPoker2** [comment]
> pip install transparent-background==1.3.2 卸载安装这个版本

for stage one, switch to clipseg and transparent background
![Screenshot (194)](https://github.com/user-attachments/assets/f036ff79-7b5e-41b3-b4c9-417c368bf5e5)
and now i'm having issues with stage 2 XD
![Screenshot (195)](https://github.com/user-attachments/assets/8419a372-8594-4d96-a1e2-2beea466474c)

**Comment by caiosabenca** [comment]
I currently have transparent background 1.3.3 and pyvirtualcam 0.12 installed in my venv and I still can't find the reason for the Ebsynth to keep failing to generate stage 1 using transparent background and when I try just the clipseg, the stage 2 fails with the same "index out of range" as @DotPoker2 

Should a downgrade of the Transparent background needed? 
My venv was built under cpython 3.10 (Windows 10)

below a screenshot of my venv and both components installed on it

![pip_freeze](https://github.com/user-attachments/assets/a1f44b84-604d-43cb-a3a0-51287b52af6d)

full message of error:
Skip frame extraction
*** Error completing request
*** Arguments: (0, 'E:\\StableDiff\\videos', 'C:\\Users\\userx\\AppData\\Local\\Temp\\gradio\\abaffd9d3acb42965201becf336a9225bcefe9ee\\video1.mp4', -1, -1, 0, 0, False, False, 'person', '', 0.4, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
    Traceback (most recent call last):
      File "E:\StableDiff\stable-diffusion-webui-master\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "E:\StableDiff\stable-diffusion-webui-master\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "E:\StableDiff\stable-diffusion-webui-master\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "E:\StableDiff\stable-diffusion-webui-master\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
        ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
      File "E:\StableDiff\stable-diffusion-webui-master\extensions\ebsynth_utility\stage1.py", line 209, in ebsynth_utility_stage1
        create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
      File "E:\StableDiff\stable-diffusion-webui-master\extensions\ebsynth_utility\stage1.py", line 151, in create_mask_transparent_background
        remover = Remover(fast=tb_use_fast_mode, jit=tb_use_jit, device=devices.get_optimal_device_name())
    TypeError: Remover.__init__() got an unexpected keyword argument 'fast'

**Comment by Idiotabtcodes** [comment]
安装transparent-background==1.3.2解决了，安装后controlnetaux显示的timm版本不兼容实测好像也没问题

**Comment by billijoquindara26** [comment]
The `TypeError: Remover.__init__() got an unexpected keyword argument 'fast'` suggests that the `transparent-background` library updated its `Remover` class signature in version 1.3.3, removing the `fast` parameter. Since downgrading to 1.3.2 resolves the initialization error, could you verify if the current codebase is explicitly passing `fast=True` during the `Remover` instantiation in your source files?

**Comment by brekenellington26** [comment]
`transparent-background` removed the `fast` parameter in 1.3.3, so you
