### ISSUE TITLE
Unable to create mask - Cannot download ckpt_base.pth

### ISSUE THREAD

**Issue by AIisCool** [s9roll7/ebsynth_utility#26]
```
frame extracted
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\stable-diffusion-webui\venv\Scripts\transparent-background.exe\__main__.py", line 7, in <module>
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transparent_background\Remover.py", line 151, in console
    remover = Remover(fast=args.fast, jit=args.jit, device=args.device, ckpt=args.ckpt)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transparent_background\Remover.py", line 79, in __init__
    self.model.load_state_dict(torch.load(os.path.join(ckpt_dir, ckpt_name), map_location='cpu'), strict=True)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MainUser\\.transparent-background\\ckpt_base.pth'
mask created

completed.
```

Went to the link, tried to download "latest.pth" but got: HTTP ERROR 429.

**Comment by nukadelic** [comment]
Downloaded the file , here is a [uploaded link](https://www.mediafire.com/file/gjvux7ys4to9b4v/latest.pth/file) if u need , any ideas which directory should i drop it into ?

**Comment by AIisCool** [comment]
@nukadelic thanks. As for where to put it I assume `C:\Users\[yourusername]\.transparent-background\`?

**Comment by nukadelic** [comment]
yep that solved it , ( had renamed the file to "ckpt_base" ) , now i finally can make masks , now to stage 2

**Comment by s9roll7** [comment]
[1e91627](https://github.com/s9roll7/ebsynth_utility/commit/1e91627c22a944710aacaa8f4a7cdd48315de144)

**Comment by sebastianf777** [comment]
> ckpt_base

God bless you my friend
