### ISSUE TITLE
Stage 2 list index out of range

### ISSUE THREAD

**Issue by ruvidan** [s9roll7/ebsynth_utility#44]
I just got ebsynth and have been having a couple of issues.  It doesn't seem to show all the videos I choose when I drag it into the video box.  So I dragged it in manually. (I have the latest ffmpeg I also have deforum extension installed and it can break apart the same videos into photos there.).  Stage 1 makes the mask but stage 2 generates an error.  I'm still pretty new so it's probably me, but what should I be looking for with this error?

fps: 30.0
key_min_gap: 10
key_max_gap: 300
key_th: 8.5
Error completing request
Arguments: (1, 'ebsynth', 'C:\\Users\\ASUS CUSTOM\\AppData\\Local\\Temp\\7c0f3a98cf7b70e12d97287d38931950ede61124\\kenalpha.mp4', -1, -1, 0, 0, False, False, '', '', 0.4, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 85, in ebsynth_utility_process
    ebsynth_utility_stage2(dbg, project_args, key_min_gap, key_max_gap, key_th, key_add_last_frame, is_invert_mask)
  File "D:\stable-diffusion-webui\extensions\ebsynth_utility\stage2.py", line 153, in ebsynth_utility_stage2
    keys = analyze_key_frames(frame_path, frame_mask_path, key_th, key_min_gap, key_max_gap, key_add_last_frame, is_invert_mask)
  File "D:\stable-diffusion-webui\extensions\ebsynth_utility\stage2.py", line 80, in analyze_key_frames
    key_frame = frames[0]
IndexError: list index out of range

**Comment by ruvidan** [comment]
And when I run stage1 transparent background it errors:

"Skip frame extraction
'transparent-background' is not recognized as an internal or external command,
operable program or batch file.
mask created"

I'm sorry, I'm sure I might be doing something wrong as I'm new to ebsynth.  But I did install it per directions (i've installed other plugins before but Ebsynth is new to me)

**Comment by chlowden** [comment]
I have been having the same issue in linux and I have solved it by taking out all spaces in the file path and file name in the project directory and original movie path

**Comment by chlowden** [comment]
What version of python do you have? I am not convinced this works with python 3.9
