### ISSUE TITLE
Walk through video

### ISSUE THREAD

**Issue by ameen-roayan** [s9roll7/ebsynth_utility#5]
Hi ! 
This is really amazing, a tutorial video is much needed though, there are many bells and whistles on this one.

**Comment by TylusKinas** [comment]
It would be nice to have some tips... I stuck on first stage :(

"stage1

Skip frame extraction
mask created

completed."

**Comment by s9roll7** [comment]
> It would be nice to have some tips... I stuck on first stage :(
> 
> "stage1
> 
> Skip frame extraction mask created
> 
> completed."
What exactly is the situation?
If the "video_frame" and "video_mask" directories are created under the project_dir, and each directory contains a disassembled video frame and a masked image, then it has succeeded.

**Comment by trendland** [comment]
Hi, Im stuck on stage 1 as well - the folders are created but not the frames - 
It says "Error: clipseg_mask_prompt is Empty" 
(ive tried all 3 masking method)

**Comment by TylusKinas** [comment]
I solved. It's ffmpeg problem.
I haven't instaled ffmpeg so script created empty folders. After instaling ffmpeg corectly I had delet empty folders and now everithing worket corectly.

**Comment by trendland** [comment]
ok, weird cause I have ffmpeg installed correctly

**Comment by trendland** [comment]
ok new error - 

/bin/sh: ffmpeg.exe: command not found
frame extracted
/bin/sh: venvScriptstransparent-background: command not found
mask created

it's trying to launch the .exe file and i'm on a mac - it might be the error :/

**Comment by TylusKinas** [comment]
For mask you shoud choose "clipseg" in seting and in text write what you thant to mask. If you dont have apha chanel.

**Comment by TylusKinas** [comment]
I think can just export img sequnce using video editing program and put to folder

**Comment by s9roll7** [comment]
> ok new error -
> 
> /bin/sh: ffmpeg.exe: command not found frame extracted /bin/sh: venvScriptstransparent-background: command not found mask created
> 
> it's trying to launch the .exe file and i'm on a mac - it might be the error :/

sorry. I don't know anything about mac.

**Comment by eranmahalu** [comment]
I am stuck on stage 2 with:

stage2

fps: 25.0
key_min_gap: 8
key_max_gap: 250
key_th: 8.5
Error completing request
Arguments: (1, 'H:\\Ebsynth_Animations\\01_MaxWomanTest\\ebsynth', 'C:\\Users\\USER\\AppData\\Local\\Temp\\1132xk9u1.mp4', -1, -1, 0, 0, False, False, '', '', 0.4, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 85, in ebsynth_utility_process
    ebsynth_utility_stage2(dbg, project_args, key_min_gap, key_max_gap, key_th, key_add_last_frame, is_invert_mask)
  File "C:\stable-diffusion-webui\extensions\ebsynth_utility\stage2.py", line 153, in ebsynth_utility_stage2
    keys = analyze_key_frames(frame_path, frame_mask_path, key_th, key_min_gap, key_max_gap, key_add_last_frame, is_invert_mask)
  File "C:\stable-diffusion-webui\extensions\ebsynth_utility\stage2.py", line 80, in analyze_key_frames
    key_frame = frames[0]
IndexError: list index out of range

**Comment by oxidizer05** [comment]
On mac you should install ffmpeg https://ffmpeg.org/
And paste your EbSynth app (https://ebsynth.com/) in Download folder /Users/your_user_name/Downloads

First test project you can create in the same location

Project directory
/Users/your_user_name/Downloads/testforebsynth

Original Movie Path
/Users/your_user_name/Downloads/testforebsynth/testvideo.mp4

**Comment by s9roll7** [comment]
I found a tutorial video
https://www.youtube.com/watch?v=Qph7A3UaVds

**Comment by AladdinFPV** [comment]
Hi, anyone knows what if we don't wanna use mask? I want to process the full image not masking anything in particular

**Comment by s9roll7** [comment]
![no_mask](https://user-images.githubusercontent.com/118420657/233825048-7b40d9a4-e8a1-4d7a-ad06-1b666708df09.png)

**Comment by AladdinFPV** [comment]
Thank you!
