### ISSUE TITLE
解决mask 空目录 empty 的问题

### ISSUE THREAD

**Issue by dundund** [s9roll7/ebsynth_utility#54]
transparent-background用的是谷歌网盘的下载源,ebsynth的mask全靠这个脚本,这个脚本有个base基础的,fast快的模型,用Chrome浏览器去下载这个,
drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link
得到一个latest.pth  然后将他改名成ckpt_base.pth,并放到C:\Users\改成自己的用户名\.transparent-background\
目录里,翻了半天源代码,梯子也没用,报错也没提路径和文件名.源代码在recover.py里面.
如果想用fast的模型,就去源代码里面翻翻下载链接,drive.google.com/file/d/1iRX-0MVbUjvAVns5MtVdng6CQlGOIo3m/view?usp=share_link
改名成ckpt_fast.pth
放上面那个目录里C:\Users\改成自己的用户名\.transparent-background\

自己找了一晚上.希望能帮到国人

**Comment by Druchii236641237** [comment]
非常有效, 我成功了

**Comment by swainchong** [comment]
> transparent-background用的是谷歌網盤的下載源,ebsynth的mask全靠這個腳,這個腳有基礎的,fast快的模型,用Chrome瀏覽器去下載這個,drive.google. com/文件 / d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link 得到一個latest.pth 然後將他改名成ckpt_base.pth,並放到C:\Users\改成自己的用戶名.transparent- background 目錄裡,翻了半天源代碼,梯子也沒有用，報錯也沒有提路徑和文件名。源碼在recover.py裡面。 如果想用fast的模型，就去源碼裡翻翻下載鏈接，drive.google.com/file/d /1iRX -0MVbUjvAVns5MtVdng6CQlGOIo3m/view?usp=share_link 改名ckpt_fast.pth 放上面那個目錄裡C:\Users\改成自己的用戶名.transparent-background\
> 
> 自己找了一個晚上。希望能幫到國人

为啥我还是不行啊，是C:\Users\用戶名.transparent-background\   还是C:\Users\用戶名\.transparent-background\,  不过都不行啊，报错是
'transparent-background' is not recognized as an internal or external command,
operable program or batch file.
mask created

**Comment by swainchong** [comment]
原来那斜杠显示不出来

**Comment by wubianluomu115** [comment]
没有这个隐藏文件啊？？！！！

**Comment by wubianluomu115** [comment]
> transparent-background用的是谷歌网盘的下载源，ebsynth的mask全靠这个脚本，这个脚本有个base基础的，fast快的模型，用Chrome浏览器去下载这个， drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link 得到一个latest.pth 然后将他改名成ckpt_base.pth，并放到C：\Users\改成自己的用户名.transparent-background 目录里，翻了半天源代码，梯子也没用，报错也没提路径和文件名.源代码在 recover.py 里面. 如果想用fast的模型，就去源代码里面翻翻下载链接，drive.google.com/file/d/1iRX-0MVbUjvAVns5MtVdng6CQlGOIo3m/view?usp=share_link 改名成ckpt_fast.pth 放上面那个目录里C：\Users\改成自己的用户名.transparent-background\
> 
> 自己找了一晚上.希望能帮到国人
不会弄啊。。。。。

**Comment by FeiJiu518** [comment]
而你，是我们的英雄！成功了呜呜呜！

**Comment by TangFenTyan** [comment]
very nice solution, love from China❤

**Comment by FTLDove** [comment]
大佬求助这是什么问题。已经改名放好文件了
Skip frame extraction
Settings -> Mode=base, Device=cpu, Torchscript=disabled
Traceback (most recent call last):
  File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\Scripts\transparent-background.exe\__main__.py", line 7, in <module>
  File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\Remover.py", line 192, in console
    loader = eval(_format + 'Loader')(args.source)
  File "<string>", line 1, in <module>
NameError: name 'Loader' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
mask created

completed.

**Comment by w11999** [comment]
怎么把切的时候用cpu改成GPU啊，cpu切的太慢了

**Comment by jiangshilin111** [comment]
请教一下 下载了ckpt_fast.pth 但是再生成蒙版时出现了下面的错 这是因为什么？
![image](https://github.com/s9roll7/ebsynth_utility/assets/104953086/66440aa0-57bd-4506-823e-5e0bb665c513)

**Comment by k186** [comment]
> 大佬求助这是什么问题。已经改名放好文件了 Skip frame extraction Settings -> Mode=base, Device=cpu, Torchscript=disabled Traceback (most recent call last): File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\Scripts\transparent-background.exe__main__.py", line 7, in File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\Remover.py", line 192, in console loader = eval(_format + 'Loader')(args.source) File "", line 1, in NameError: name 'Loader' is not defined 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。 mask created
> 
> completed.

清空输出文件夹 重新跑

**Comment by dundund** [comment]
name 'Loader' is not defined,加载器没有被定义,你跟着教程重新走吧,新项目.资源没有报错.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月30日(星期五) 中午11:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [s9roll7/ebsynth_utility] 解决mask 空目录 empty 的问题 (Issue #54)





  
大佬求助这是什么问题。已经改名放好文件了 Skip frame extraction Settings -&gt; Mode=base, Device=cpu, Torchscript=disabled Traceback (most recent call last): File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return run_code(code, main_globals, None, File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code exec(code, run_globals) File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\Scripts\transparent-background.exe__main.py", line 7, in File "C:\Users\Avicii\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\Remover.py", line 192, in console loader = eval(_format + 'Loader')(args.source) File "", line 1, in NameError: name 'Loader' is not defined 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。 mask created
 
completed.
  
清空输出文件夹 重新跑

**Comment by ZWQ26** [comment]
而你，才是我的英雄

**Comment by T-Shu** [comment]
怎么把cpu改成GPU啊，cpu太慢了

**Comment by hydra-li** [comment]
> transparent-background用的是谷歌网盘的下载源,ebsynth的mask全靠这个脚本,这个脚本有个base基础的,fast快的模型,用Chrome浏览器去下载这个, drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link 得到一个latest.pth 然后将他改名成ckpt_base.pth,并放到C:\Users\改成自己的用户名.transparent-background 目录里,翻了半天源代码,梯子也没用,报错也没提路径和文件名.源代码在recover.py里面. 如果想用fast的模型,就去源代码里面翻翻下载链接,drive.google.com/file/d/1iRX-0MVbUjvAVns5MtVdng6CQlGOIo3m/view?usp=share_link 改名成ckpt_fast.pth 放上面那个目录里C:\Users\改成自己的用户名.transparent-background\
> 
> 自己找了一晚上.希望能帮到国人

请问必须是Chrome下载吗？我是mac电脑，按照这个操作做了，还是报错

**Comment by wuxin-hun** [comment]
> 怎么把切的时候用cpu改成GPU啊，cpu切的太慢了

我也是，请问找到解决办法了吗

**Comment by 8410ttt** [comment]
超级感谢！

**Comment by lisir0528** [comment]
超级感谢！

**Comment by ssy09060137** [comment]
让我试一试
