### ISSUE TITLE
Stage 1 stops after generating video frame

### ISSUE THREAD

**Issue by nunch31** [s9roll7/ebsynth_utility#68]
When I run Stage 1,
After generating the video frame,
it dosn't longer works with the following error code.
This is happening after this update.

I'm running this using Google Collab.
It was working fine until this update.

Thanks for the update.

____________________________________________________________________________________________________________________________

SDWebUI: frame extracted
SDWebUI: Error completing request
SDWebUI: Arguments: (0, '/content/drive/MyDrive/SD/eb', '/content/drive/MyDrive/SD/eb/ori.mp4', -1, -1, 0, 0, False, False, '', '', 0.4, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
SDWebUI: Traceback (most recent call last):
SDWebUI:   File "/content/sd-webui/modules/call_queue.py", line 56, in f
SDWebUI:     res = list(func(*args, **kwargs))
SDWebUI:   File "/content/sd-webui/modules/call_queue.py", line 37, in f
SDWebUI:     res = func(*args, **kwargs)
SDWebUI:   File "/content/sd-webui/extensions/ebsynth_utility/ebsynth_utility.py", line 79, in ebsynth_utility_process
SDWebUI:     ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
SDWebUI:   File "/content/sd-webui/extensions/ebsynth_utility/stage1.py", line 216, in ebsynth_utility_stage1
SDWebUI:     create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
SDWebUI:   File "/content/sd-webui/extensions/ebsynth_utility/stage1.py", line 150, in create_mask_transparent_background
SDWebUI:     venv = os.environ['VIRTUAL_ENV']
SDWebUI:   File "/usr/lib/python3.10/os.py", line 680, in __getitem__
SDWebUI:     raise KeyError(key) from None
SDWebUI: KeyError: 'VIRTUAL_ENV'
SDWebUI

**Comment by s9roll7** [comment]
thnx for report
I can't test it right now, but I think it can be fixed by modifying the code as follows.

```
    venv = os.environ['VIRTUAL_ENV']
    if not venv:
        venv = "venv"
    bin_path = os.path.join(venv, "Scripts")
```

**Comment by UriahKong** [comment]
same problem happened to me ,plz I am helpless

**Comment by UriahKong** [comment]
> thnx for report I can't test it right now, but I think it can be fixed by modifying the code as follows.
> 
> ```
>     venv = os.environ['VIRTUAL_ENV']
>     if not venv:
>         venv = "venv"
>     bin_path = os.path.join(venv, "Scripts")
> ```

cheers mate ,plz how do I modify this code

**Comment by UriahKong** [comment]
- Error completing request
Arguments: (0, 'C:\\Users\\Administrator\\Videos\\555', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\gradio\\dbbde2ec422c69f3c7e8d31d20198bcdcce03a2d\\s56d4a.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
Traceback (most recent call last):
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
    ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 216, in ebsynth_utility_stage1
    create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 150, in create_mask_transparent_background
    venv = os.environ['VIRTUAL_ENV']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'VIRTUAL_ENV'

**Comment by UriahKong** [comment]
> Error completing request
Arguments: (0, 'C:\\Users\\Administrator\\Videos\\555', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\gradio\\dbbde2ec422c69f3c7e8d31d20198bcdcce03a2d\\s56d4a.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
Traceback (most recent call last):
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
    ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 216, in ebsynth_utility_stage1
    create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 150, in create_mask_transparent_background
    venv = os.environ['VIRTUAL_ENV']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'VIRTUAL_ENV'

**Comment by UriahKong** [comment]
`Error completing request
Arguments: (0, 'C:\\Users\\Administrator\\Videos\\555', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\gradio\\dbbde2ec422c69f3c7e8d31d20198bcdcce03a2d\\s56d4a.mp4', -1, -1, 0, 0, False, False, '', '', 0, 11, 11, 10, 300, 8.5, True, 'hm-mkl-hm', True, False, False, 0, None, 1, 'mp4', '', 'Fit video length', 5, 0, 0, 'Normal') {}
Traceback (most recent call last):
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 79, in ebsynth_utility_process
    ebsynth_utility_stage1(dbg, project_args, frame_width, frame_height, st1_masking_method_index, st1_mask_threshold, tb_use_fast_mode, tb_use_jit, clipseg_mask_prompt, clipseg_exclude_prompt, clipseg_mask_threshold, clipseg_mask_blur_size, clipseg_mask_blur_size2, is_invert_mask)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 216, in ebsynth_utility_stage1
    create_mask_transparent_background(frame_path, frame_mask_path, tb_use_fast_mode, tb_use_jit, st1_mask_threshold)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 150, in create_mask_transparent_background
    venv = os.environ['VIRTUAL_ENV']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'VIRTUAL_ENV'`

**Comment by s9roll7** [comment]
It was unintentionally auto-closed...
If you still have problems, please reopen it.

**Comment by UriahKong** [comment]
> It was unintentionally auto-closed... If you still have problems, please reopen it.

Sir,I did reopen it in many times ,before this error happened I deleted the old version of ebsynth_utility and downloaded the newest version ,Sir,plz give me a clue ,I'm really appreciated

**Comment by s9roll7** [comment]
Sorry, I was sleepwalking.
I think it's fixed now.

**Comment by UriahKong** [comment]
> Sorry, I was sleepwalking. I think it's fixed now.

Now it works !mate,I love it ,ur my hero ,thankkkkkku
