### ISSUE TITLE
Masks Generation is skipped, OSError: unrecognized data stream contents when reading image file

### ISSUE THREAD

**Issue by Jetbleu** [s9roll7/ebsynth_utility#69]
I'm having this error while trying to create the masks for the Step 1 

```
Settings -> Mode=base, Device=cuda:0, Torchscript=disabled
00010.png:       3%|█▋                                                | 10/287 [00:08<03:31,  1.31it/s]Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\venv\Scripts\transparent-background.exe\__main__.py", line 7, in <module>
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transparent_background\Remover.py", line 197, in console
    for img, name in loader:
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transparent_background\utils.py", line 134, in __next__
    img = Image.open(self.images[self.index]).convert('RGB')
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 933, in convert
    self.load()
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 288, in load
    raise_oserror(err_code)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 72, in raise_oserror
    raise OSError(msg)
OSError: unrecognized data stream contents when reading image file
mask created
```

Is it normal to have Torschscript as disabled?

**Comment by Jetbleu** [comment]
Sorry, I solved it by reinstalling the extension, I think my antivirus blocked something in the first run
