### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for transparent-background on Automatic1111 startup

### ISSUE THREAD

**Issue by ElizaPottinger** [s9roll7/ebsynth_utility#73]
Hey there, I am getting following message in the CLI when starting automatic1111 with the Ebysnth_utility extension active. I am not getting the tab to show up in automatic1111. Tried installing transparent-background with "pip install transparent-background" but the error still persists. How do I get it to work?

Error running install.py for extension E:\stable-diffusion-webui\extensions\ebsynth_utility.
Command: "E:\stable-diffusion-webui\venv\Scripts\python.exe" "E:\stable-diffusion-webui\extensions\ebsynth_utility\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\ebsynth_utility\install.py", line 14, in <module>
    update_transparent_background()
  File "E:\stable-diffusion-webui\extensions\ebsynth_utility\install.py", line 6, in update_transparent_background
    v = meta_version("transparent-background")
  File "C:\Users\Eliza\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 996, in version    return distribution(distribution_name).version
  File "C:\Users\Eliza\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\Eliza\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for transparent-background

**Comment by ElizaPottinger** [comment]
User error:
had --skip-install in my webui-user.bat
