### ISSUE TITLE
extention doesn't see an ffmpeg

### ISSUE THREAD

**Issue by Webthrinity** [s9roll7/ebsynth_utility#78]
"ffmpeg" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
frame extracted
Settings -> Mode=base, Device=cuda:0, Torchscript=disabled
Traceback (most recent call last):
  File "C:\stable-diffusion-portable-main\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\stable-diffusion-portable-main\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\stable-diffusion-portable-main\venv\Scripts\transparent-background.exe\__main__.py", line 7, in <module>
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\transparent_background\Remover.py", line 192, in console
    loader = eval(_format + 'Loader')(args.source)
  File "<string>", line 1, in <module>
NameError: name 'Loader' is not defined
mask created

completed.

But i've already installed ffmpeg and when i check the version of it in cdm i see 

2023-06-15-git-41229ef705-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58. 13.100 / 58. 13.100
libavcodec     60. 18.100 / 60. 18.100
libavformat    60.  6.100 / 60.  6.100
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  8.101 /  9.  8.101
libswscale      7.  3.100 /  7.  3.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100

**Comment by jay1803** [comment]
use the command `which ffmpeg`
you will get the path of ffmpeg, copy the folder path, then open the `environment.bat` in sd.webui, append the folder path to the `set PATH=`

for example:
when you run 
```
which ffmpeg
// output
C:/Users/your_folder_path/ffmpeg.exe
```

Then copy the `C:/Users/your_folder_path`

Open the `environment.bat` find the set PATH line, 
like `set PATH=C:\Windows\system32;C:\Windows;%DIR%\git\bin;%DIR%\python;%DIR%\python\Scripts`

Then append ffmpeg folder path at the end of the `set PATH` line, don't forgot to use prefix a `;`
`set PATH=C:\Windows\system32;C:\Windows;%DIR%\git\bin;%DIR%\python;%DIR%\python\Scripts;C:/Users/your_folder_path`
