### ISSUE TITLE
Settings -> Mode=base, Device=cpu, Torchscript=disabled

### ISSUE THREAD

**Issue by baby11233** [s9roll7/ebsynth_utility#82]

**Comment by baby11233** [comment]
Traceback (most recent call last):
  File "C:\Users\cnscz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cnscz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cnscz\AppData\Local\Programs\Python\Python310\Scripts\transparent-background.exe\__main__.py", line 7, in <module>
  File "C:\Users\cnscz\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\Remover.py", line 192, in console
    loader = eval(_format + 'Loader')(args.source)
  File "<string>", line 1, in <module>
NameError: name 'Loader' is not defined

**Comment by qujinyu** [comment]
请问是怎么修改的？
