### ISSUE TITLE
Errors shown

### ISSUE THREAD

**Issue by Knell2231** [s9roll7/ebsynth_utility#9]
Traceback (most recent call last):
  File "K:\Misc\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "K:\Misc\Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "K:\Misc\Automatic1111\stable-diffusion-webui\extensions\ebsynth_utility\scripts\ui.py", line 4, in <module>
    from ebsynth_utility import ebsynth_utility_process
  File "K:\Misc\Automatic1111\stable-diffusion-webui\extensions\ebsynth_utility\ebsynth_utility.py", line 8, in <module>
    from extensions.ebsynth_utility.stage1 import ebsynth_utility_stage1,ebsynth_utility_stage1_invert
  File "K:\Misc\Automatic1111\stable-diffusion-webui\extensions\ebsynth_utility\stage1.py", line 7, in <module>
    from transformers import AutoProcessor, CLIPSegForImageSegmentation
ImportError: cannot import name 'CLIPSegForImageSegmentation' from 'transformers' (K:\Misc\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)

the tab also doesn't show up in the UI

**Comment by s9roll7** [comment]
It seems that clipseg was added to transformers 4 months ago. Perhaps the transformers in your environment are too old.
