### ISSUE TITLE
Can't extract frames or do anything...am I doing something wrong?

### ISSUE THREAD

**Issue by chimera15** [s9roll7/ebsynth_utility#99]
My ebsynth utility in automatic1111 seems completely broken.  I can't extract frames and the script fails as well when I extract the frames using a different app. 

This is what I get when I try to extract frames of a video. 

ERROR:    Exception in ASGI application████████████████████████████████████████████████| 48/48 [00:23<00:00,  2.01it/s]
Traceback (most recent call last):
  File "L:\supersd2\stabdif3\venv\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "L:\supersd2\stabdif3\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\gradio\routes.py", line 531, in join_queue
    session_info = await asyncio.wait_for(
  File "C:\Users\lrdce\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "L:\supersd2\stabdif3\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

**Comment by chimera15** [comment]
hmm 

User avatar
level 1
[zerozeroZiilch](https://www.reddit.com/user/zerozeroZiilch/)
·
[2 mo. ago](https://www.reddit.com/r/StableDiffusion/comments/11w01s9/comment/jjywktn/?utm_source=reddit&utm_medium=web2x&context=3)

Figured out whats going on with this scenario and error code. You absolutely must have the project folder be empty, so delete the folders it created that were empty if it failed and your retrying, I initially got into this issue because I had the mp4 i wanted processed located in the project folder. Thankfully github pointed me to the solution. Also make sure FFMpeg is properly installed. Any other issues are related directly with FFmpeg, I currently have a different error with FFmpeg 6.0 installed and fully updated but I'm getting " Invalid data found when processing input" which is a different issue.

**Comment by chimera15** [comment]
ok yup I moved it to c drive and cleared all the folders that seemed to work.  so weird.

**Comment by chimera15** [comment]
Traceback (most recent call last):
      File "L:\supersd2\stabdif3\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "L:\supersd2\stabdif3\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "L:\supersd2\stabdif3\modules\img2img.py", line 196, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "L:\supersd2\stabdif3\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
      File "L:\supersd2\stabdif3\extensions\ebsynth_utility\scripts\custom_script.py", line 808, in run
        return Processed()
    TypeError: Processed.__init__() missing 2 required positional arguments: 'p' and 'images_list'
    
    now I'm at this.

**Comment by chimera15** [comment]
I think I managed to get around it with just batching the folder....but I can't get the script to work, so no mask will work.

**Comment by noanymore** [comment]
have you resolved it ?  i met the problem too
